 server:
  port: 9090
 spring:
  application:
    name: networkticketingapplicationproject
  security:
    user:
     name: root
     password: password
  datasource:
    url: jdbc:mysql://localhost:3306/networkticketapplicationdb?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

 networkticketapp:
   jwtSecret: BLUEYONDERBELLANDURBENGALURUBLUEYONDERBELLANDURBENGALURUBLUEYONDERBELLANDURBENGALURUBENGALURUBLUEYONDERBELLANDURBENGALURUBENGALURUBLUEYONDERBELLANDURBENGALURU
   jwtExpirationMs: 86400000
   
   logging:
   file:
    name: logs/app.log
   logback:
    rollingpolicy:
      file-name-pattern: logs/%d{yyyy-MM, aux}/app.%d{yyyy-MM-dd}.%i.log
      max-file-size: 100MB
      total-size-cap: 10GB
      max-history: 10   
   
   